spring:
  application:
    name: modulith.cqrs
  datasource:
    command:
      jdbc-url: jdbc:h2:mem:commanddb
      username: sa
      password:
      driver-class-name: org.h2.Driver
    query:
      jdbc-url: jdbc:h2:mem:querydb
      username: sa
      password:
      driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  modulith:
    events:
      jdbc:
        schema-initialization:
          enabled: true
        schema: querydb
      republish-outstanding-events-on-restart: true


logging:
  level:
    gae.piaz.modulith.cqrs: DEBUG
    org.springframework.modulith: DEBUG